import { Connection, PublicKey } from "@solana/web3.js";
// Anchor 1.0 (April 2026) moved the TS client package from
// @coral-xyz/anchor to @anchor-lang/core. Same exported API (per the
// migration notes) — just a new package name. If you're following an
// older tutorial that imports from @coral-xyz/anchor, that package is
// still published (frozen at 0.32.1) but is the legacy pre-1.0 line.
import { AnchorProvider, Program, Wallet } from "@anchor-lang/core";
import { CONFIG } from "@stockflow/common";

// IDL is generated by `anchor build` into target/idl/stockflow.json and
// should be copied here as part of the build pipeline. Placeholder path
// kept so the SDK compiles before the program is first built.
// import idl from "./idl/stockflow.json";

export interface StockFlowClientOptions {
  connection: Connection;
  wallet: Wallet;
  programId?: PublicKey;
}

export class StockFlowClient {
  public readonly connection: Connection;
  public readonly wallet: Wallet;
  public readonly programId: PublicKey;
  public readonly provider: AnchorProvider;
  // public readonly program: Program;

  constructor(opts: StockFlowClientOptions) {
    this.connection = opts.connection;
    this.wallet = opts.wallet;
    this.programId = opts.programId ?? CONFIG.devnet.stockflowProgramId;
    this.provider = new AnchorProvider(this.connection, this.wallet, {
      commitment: "confirmed",
    });
    // this.program = new Program(idl as any, this.programId, this.provider);
  }
}
